services:
  go_api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: song_api
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: song_db
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:1.25
    container_name: song_nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - go_api

volumes:
  pgdata:
