services:
  go_api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: song_api
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:12345@db:5432/songdb?sslmode=disable
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: song_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: songdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  nginx:
    image: nginx:1.25
    container_name: song_nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - go_api

volumes:
  pgdata:
